//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhNhan_PhongKhamDaKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        public string MABN { get; set; }
        public string TENBN { get; set; }
        public Nullable<int> TUOIBN { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string SDTBN { get; set; }
        public string BHYT { get; set; }
    }
}
