use QUANLYBENHNHAN

CREATE PROC DS_BN
AS 
BEGIN
SELECT MABN AS N'MĂ BỆNH NHÂN', TENBN AS N'TÊN BỆNH NHÂN', TUOIBN AS N'TUỔI', GIOITINH AS N'GIỚI TÍNH', DIACHI AS N'ĐỊA CHỈ', SDTBN AS N'SỐ ĐIỆN THOẠI', BHYT AS 'BHYT'
FROM BENHNHAN
END

EXEC DS_BN

UPDATE BENHNHAN SET TUOIBN = '30' WHERE MABN = 'BN001'